/* Guided, curated recommendations. No remote AI or inferred construction measurements. */
(()=>{'use strict';
const roomNames={living:'Salón',kitchen:'Cocina',bath:'Baño',bedroom:'Dormitorio',dining:'Comedor',balcony:'Terraza'};
const tastes={light:{label:'Claro y sereno',styles:['nordico','japandi','minimalista'],why:'Una base clara, poco contraste y materiales suaves.'},warm:{label:'Cálido y natural',styles:['calido','mediterraneo','organicmodern'],why:'Maderas, tonos tierra y texturas para un ambiente acogedor.'},bold:{label:'Elegante y con contraste',styles:['contemporaneo','artdeco','quietluxury'],why:'Tonos profundos y acabados contrastados, equilibrados con luz.'},color:{label:'Color y personalidad',styles:['midcentury','eclectic','boho'],why:'Una base combinable con acentos de color, arte y textiles.'}};
const launch=document.createElement('div');launch.className='advisor-entry';launch.innerHTML='<div><span class="eyebrow">GUÍA DE ESTILO</span><h2>¿No sabes por dónde empezar?</h2><p>Elige cómo quieres sentir tu espacio y compara tres combinaciones coordinadas.</p></div><button class="btn btn-dark" id="openStyleGuide">Ayúdame a elegir</button>';
$('#view-inspiration .look-toolbar').before(launch);$('#openStyleGuide').onclick=()=>openGuide();$('#suggestDesign').textContent='Guía de estilo';$('#suggestDesign').onclick=()=>openGuide(true);
function openGuide(useCurrent=false){const current=selectedRoom();$('#modalContent').innerHTML=`<span class="eyebrow">GUÍA DE ESTILO · COMBINACIONES CURADAS</span><h2>Tu espacio empieza contigo.</h2><form id="styleGuideForm" class="advisor-form"><label>¿Dónde lo aplicarás?<select id="guideRoom" aria-label="Estancia para la guía">${Object.entries(roomNames).map(([k,l])=>`<option value="new:${k}">Nueva estancia: ${l}</option>`).join('')}${project.rooms.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · existente</option>`).join('')}</select></label><fieldset><legend>¿Qué ambiente te gustaría?</legend><div class="advisor-tastes">${Object.entries(tastes).map(([k,t],i)=>`<label><input type="radio" name="guideTaste" value="${k}" ${i===1?'checked':''}><span>${t.label}</span></label>`).join('')}</div></fieldset><label>¿Qué prefieres priorizar?<select id="guidePriority"><option value="balanced">Una combinación equilibrada</option><option value="clean">Superficies fáciles de limpiar</option><option value="natural">Texturas naturales</option></select></label><button type="submit" class="btn btn-dark">Ver mis tres propuestas</button></form><div id="guideResults" aria-live="polite"></div>`;if(useCurrent&&current)$('#guideRoom').value=current.id;$('#modal').classList.add('open');$('#styleGuideForm').onsubmit=e=>{e.preventDefault();showResults()};$('#styleGuideForm').onchange=()=>{const results=$('#guideResults');if(results.children.length)results.innerHTML='<p>Has cambiado tus preferencias. Pulsa «Ver mis tres propuestas» para actualizar las combinaciones antes de aplicarlas.</p>'};}
function showResults(){const target=$('#guideRoom').value,kind=target.startsWith('new:')?target.slice(4):roomType(project.rooms.find(r=>r.id===target)),taste=tastes[$('input[name="guideTaste"]:checked').value],priority=$('#guidePriority').value;
const proposals=taste.styles.map((id,i)=>{const style=styleOptions.find(s=>s.id===id);let floor=style.floor;if(kind==='bath'||kind==='balcony')floor=i===1?'Porcelánico antideslizante':'Porcelánico marfil';else if(priority==='clean'||kind==='kitchen')floor=i===1?'Porcelánico cemento':'Porcelánico marfil';else if(priority==='natural')floor=['Roble natural','Bambú natural','Corcho natural'][i];const f=floorOptions.find(x=>x.name===floor);return {style,floor:f,reason:kind==='bath'||kind==='balcony'?'Referencia cerámica: verifica resistencia al deslizamiento, agua y uso concreto con la ficha del producto.':priority==='clean'?'Una superficie cerámica como punto de partida; comprueba juntas, acabado y mantenimiento.':priority==='natural'?'Da protagonismo a madera, lino y texturas minerales; revisa sus cuidados antes de elegir.':taste.why}});
$('#guideResults').innerHTML=`<h3>Tres formas de diseñar tu ${roomNames[kind].toLowerCase()}</h3><p>Combinaciones de nuestro catálogo. Puedes cambiar cada acabado después.</p><div class="advisor-results">${proposals.map((p,i)=>`<article><div class="advisor-swatches" aria-label="Colores de pared y suelo"><i style="background:${p.style.wall}"></i><i style="background:${p.floor.color}"></i></div><h4>${p.style.name}</h4><dl><dt>Pared</dt><dd>${p.style.wallName}</dd><dt>Suelo</dt><dd>${p.floor.name}</dd></dl><p>${p.reason}</p><button type="button" class="btn btn-light" data-guide-apply="${i}">Usar ${p.style.name}</button></article>`).join('')}</div>`;
$$('[data-guide-apply]').forEach(b=>b.onclick=()=>{const p=proposals[Number(b.dataset.guideApply)];checkpoint();if(target.startsWith('new:'))createDesignRoom(false,roomNames[kind],kind);else project.selectedRoom=project.rooms.findIndex(r=>r.id===target);loadDesignDraft(selectedRoom());designDraft={...designDraft,style:p.style.id,wallColor:p.style.wall,wallName:p.style.wallName,material:p.floor.name,floorKind:p.floor.kind,floorColor:p.floor.color};storeDesignDraft();$('#modal').classList.remove('open');goView('design');$('[data-photo-tab="concept"]')?.click();setDesignCategory('estilo');toast('Propuesta aplicada al borrador. Ajusta los acabados y guarda cuando quieras.');});$('#guideResults').scrollIntoView({behavior:'smooth',block:'nearest'});}
// Modal focus lifecycle for all existing flows, including keyboard-only use.
let returnFocus=null;const backdrop=$('#modal'),dialog=backdrop.querySelector('[role="dialog"]');new MutationObserver(()=>{if(backdrop.classList.contains('open')){returnFocus=document.activeElement;requestAnimationFrame(()=>{const title=$('#modalContent h2');if(title){title.id='activeDialogTitle';dialog.setAttribute('aria-labelledby',title.id)}(dialog.querySelector('input:not([type=hidden]),select,button:not(#closeModal)')||dialog).focus()})}else if(returnFocus?.isConnected){returnFocus.focus();returnFocus=null}}).observe(backdrop,{attributes:true,attributeFilter:['class']});backdrop.addEventListener('keydown',e=>{if(e.key==='Escape'){backdrop.classList.remove('open');return}if(e.key!=='Tab')return;const items=[...dialog.querySelectorAll('button,input,select,textarea,a[href],[tabindex="0"]')].filter(x=>!x.disabled&&x.getClientRects().length);if(!items.length){e.preventDefault();dialog.focus();return}const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
})();
