/* HomeAI: a personal shortlist built from the live catalog, never a second catalog. */
(() => {
  'use strict';
  const storageKey='homeai.catalog.favorites.v16';
  let favorites=new Set();
  try {const saved=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(saved))favorites=new Set(saved.filter(x=>typeof x==='string'));} catch {}
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const attributes=['style','dcolor','wallfinish','floorName','bath','faucet','homeaiPalette'];
  const selector='[data-style],[data-dcolor],[data-wallfinish],[data-floor-name],[data-bath],[data-faucet],[data-homeai-palette]';
  const search=document.getElementById('catalogSearch');
  if(!search)return;
  const shortlist=document.createElement('details');shortlist.className='v16-shortlist';
  shortlist.innerHTML='<summary><span aria-hidden="true">♡</span> Mis favoritos <b class="v16-total">0</b></summary><div class="v16-shortlist-body"><p>Guarda ideas sin cambiar tu diseño. Tus favoritos se conservan en este navegador.</p><label class="v16-find-label">Buscar en mis favoritos<input type="search" placeholder="Ej. roble, azul, lino" aria-label="Buscar en mis favoritos"></label><div class="v16-favorite-results" aria-live="polite"></div><div class="v16-favorite-grid"></div></div>';
  document.querySelector('.catalog-search').after(shortlist);
  const favoriteSearch=shortlist.querySelector('input');favoriteSearch.oninput=renderShortlist;
  const suggestions=document.createElement('div');suggestions.className='v16-search-ideas';suggestions.setAttribute('role','group');suggestions.setAttribute('aria-label','Ideas para buscar');
  const hint=document.createElement('span');hint.textContent='Prueba:';suggestions.append(hint);
  for(const term of ['Roble','Salvia','Lino','Mármol','Latón']){const b=document.createElement('button');b.type='button';b.textContent=term;b.onclick=()=>{search.value=term;filterCatalog();search.focus({preventScroll:true})};suggestions.append(b)}
  document.querySelector('.catalog-search').after(suggestions);
  const live=document.createElement('div');live.className='v16-sr';live.setAttribute('role','status');shortlist.append(live);
  function entry(card){const attribute=attributes.find(k=>card.dataset[k]!==undefined);return {key:attribute+':'+card.dataset[attribute],name:card.getAttribute('aria-label')||card.querySelector('.style-card-copy b')?.textContent||card.querySelector(':scope > b')?.textContent||card.textContent.trim().replace(/✓/g,'').trim(),card,category:card.closest('[data-panel]')?.dataset.panel||'pared'};}
  function entries(){const list=[...document.querySelectorAll('.design-catalog-panel '+selector.split(',').join(',.design-catalog-panel '))].map(entry);for(const select of document.querySelectorAll('.design-catalog-panel select[data-decor],.design-catalog-panel select[data-bath-detail],.design-catalog-panel select[data-room-detail]')){const type=select.dataset.decor?'decor':select.dataset.bathDetail?'bathDetail':'roomDetail',field=select.dataset.decor||select.dataset.bathDetail||select.dataset.roomDetail;for(const option of select.options){if(!option.value)continue;list.push({key:type+':'+field+':'+option.value,name:option.textContent,detail:select.getAttribute('aria-label'),select,value:option.value,category:select.closest('[data-panel]').dataset.panel})}}return list;}
  function persist(){try{localStorage.setItem(storageKey,JSON.stringify([...favorites]));return true}catch{return false}}
  function toggle(item){if(favorites.has(item.key)){favorites.delete(item.key);live.textContent=item.name+' eliminado de favoritos.'}else{favorites.add(item.key);live.textContent=item.name+' guardado en favoritos.'}if(!persist())live.textContent+=' No se pudo guardar en este navegador; se conserva durante esta sesión.';refreshStars();renderShortlist()}
  function decorate(){for(const card of document.querySelectorAll('.design-catalog-panel '+selector.split(',').join(',.design-catalog-panel '))){if(card.parentElement.classList.contains('v16-catalog-item'))continue;const wrap=document.createElement('div');wrap.className='v16-catalog-item';if(card.matches('.option-chip,.color-option'))wrap.classList.add('v16-compact');card.before(wrap);wrap.append(card);const star=document.createElement('button');star.type='button';star.className='v16-favorite-toggle';star.onclick=()=>toggle(entry(card));wrap.append(star)}
    for(const select of document.querySelectorAll('.design-catalog-panel select[data-decor],.design-catalog-panel select[data-bath-detail],.design-catalog-panel select[data-room-detail]')){const label=select.closest('label');if(label.parentElement.classList.contains('v16-field-wrap'))continue;const wrap=document.createElement('div');wrap.className='v16-field-wrap';label.before(wrap);wrap.append(label);const b=document.createElement('button');b.type='button';b.className='v16-field-save';b.onclick=()=>{const item=entries().find(x=>x.select===select&&x.value===select.value);if(item)toggle(item)};wrap.append(b);select.addEventListener('change',()=>{refreshStars();renderShortlist()})}
    refreshStars();syncHidden();renderShortlist();
  }
  function refreshStars(){for(const wrap of document.querySelectorAll('.v16-catalog-item')){const item=entry(wrap.firstElementChild),b=wrap.lastElementChild,selected=favorites.has(item.key);b.textContent=selected?'♥':'♡';b.setAttribute('aria-pressed',String(selected));b.setAttribute('aria-label',(selected?'Quitar de':'Guardar en')+' favoritos: '+item.name);b.title=(selected?'Quitar de':'Guardar en')+' favoritos'}
    const all=entries();for(const wrap of document.querySelectorAll('.v16-field-wrap')){const select=wrap.querySelector('select'),b=wrap.lastElementChild,item=all.find(x=>x.select===select&&x.value===select.value),selected=item&&favorites.has(item.key);b.disabled=!item;b.textContent=selected?'♥ En favoritos':'♡ Guardar esta opción';b.setAttribute('aria-pressed',String(!!selected));b.setAttribute('aria-label',item?(selected?'Quitar de':'Guardar en')+' favoritos: '+item.name:'Elige una opción para guardarla')}
  }
  function syncHidden(){document.querySelectorAll('.v16-catalog-item').forEach(w=>w.hidden=w.firstElementChild.hidden);document.querySelectorAll('.v16-field-wrap').forEach(w=>w.hidden=w.firstElementChild.hidden||w.firstElementChild.classList.contains('pro-not-relevant'))}
  function renderShortlist(){const known=entries(),query=norm(favoriteSearch.value),items=known.filter(x=>favorites.has(x.key)),unique=[...new Map(items.map(x=>[x.key,x])).values()],shown=unique.filter(x=>norm(x.name+' '+(x.detail||'')).includes(query));shortlist.querySelector('.v16-total').textContent=String(favorites.size);const count=shortlist.querySelector('.v16-favorite-results');count.textContent=!favorites.size?'Todavía no hay favoritos. Pulsa ♡ junto a una opción del catálogo.':!shown.length?'No hay favoritos disponibles con esta búsqueda para la estancia actual.':shown.length+' favoritos disponibles para esta estancia';const grid=shortlist.querySelector('.v16-favorite-grid');grid.replaceChildren();for(const item of shown){const article=document.createElement('article');article.className='v16-favorite-card';const preview=item.card?.querySelector('.style-art,.material-preview,.bath-preview,.homeai-palette-swatches,.color-option > i');if(preview){const visual=preview.cloneNode(true);visual.setAttribute('aria-hidden','true');visual.classList.add('v16-favorite-preview');for(const prop of ['--sample-wall','--material-color','--bath-tone','--swatch']){const value=item.card.style.getPropertyValue(prop);if(value)visual.style.setProperty(prop,value)}if(item.card.dataset.dcolor)visual.style.background=item.card.dataset.dcolor;article.append(visual)}const title=document.createElement('b');title.textContent=item.name;article.append(title);const small=document.createElement('small');small.textContent=item.detail||({estilo:'Estilo',pared:'Pared y paleta',suelo:'Suelo',banio:'Baño',decoracion:'Decoración'}[item.category]);article.append(small);const apply=document.createElement('button');apply.type='button';apply.className='v16-use-favorite';apply.textContent='Usar esta opción';const irrelevant=item.category==='banio'&&roomType(selectedRoom())!=='bath'||item.select?.closest('label')?.classList.contains('pro-not-relevant');apply.disabled=irrelevant;if(irrelevant)apply.textContent='No corresponde a esta estancia';apply.onclick=()=>{search.value='';setDesignCategory(item.category);filterCatalog();if(item.card)item.card.click();else{item.select.value=item.value;item.select.dispatchEvent(new Event('change',{bubbles:true}))}toast(item.name+' aplicada al borrador.');};const remove=document.createElement('button');remove.type='button';remove.className='v16-remove-favorite';remove.textContent='Quitar';remove.setAttribute('aria-label','Quitar de favoritos: '+item.name);remove.onclick=()=>{toggle(item);favoriteSearch.focus({preventScroll:true})};article.append(apply,remove);grid.append(article)}}
  const previousFilter=filterCatalog;filterCatalog=function(...args){const result=previousFilter.apply(this,args);syncHidden();return result};search.oninput=()=>filterCatalog();
  const previousRender=renderDesign;renderDesign=function(...args){const result=previousRender.apply(this,args);decorate();return result};
  // Saving a design rebuilds the room detail fields without a full design render.
  const previousFinishList=renderFinishList;renderFinishList=function(...args){const result=previousFinishList.apply(this,args);decorate();return result};
  window.addEventListener('storage',event=>{if(event.key===storageKey){try{const value=JSON.parse(event.newValue||'[]');favorites=new Set(Array.isArray(value)?value.filter(x=>typeof x==='string'):[])}catch{favorites=new Set()}refreshStars();renderShortlist()}});
  decorate();
})();
