/* HomeAI material library: selection is a design decision, never a product certification. */
(()=>{'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],safe=esc;
const kinds={wood:'Tablas de madera',lightwood:'Madera clara',smokedwood:'Madera ahumada',darkwood:'Madera oscura',herringbone:'Espiga',parquet:'Parqué',marble:'Veteado',stone:'Piedra',slate:'Pizarra',terrazzo:'Terrazo',hydraulic:'Hidráulico',microcement:'Continuo',concrete:'Cemento',tile:'Baldosa',textile:'Textil / liso'};
let tab='floors',query='',family='all',compare=[],target='';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const validColor=c=>/^#[0-9a-f]{6}$/i.test(c||'')?c:'#c8bba7';
function custom(){return (Array.isArray(project.customMaterials)?project.customMaterials:[]).filter(x=>x&&typeof x.id==='string'&&typeof x.name==='string').map(x=>({...x,color:validColor(x.color),kind:Object.hasOwn(kinds,x.kind)?x.kind:'tile',custom:true}));}
function allFloors(){return [...floorOptions.map((x,i)=>({...x,id:'floor-'+i})),...custom()];}
function facts(x){const n=norm(x.name);if(x.custom)return{family:'Propio',care:'Consulta la ficha de limpieza del producto.',wet:'Por confirmar con el proveedor y el instalador.',install:'Registra soporte, espesor, formato y sistema de colocación.',note:x.note||'Añade tus observaciones al editar este material.'};
if(/laminado/.test(n))return{family:'Laminado',care:'Limpieza poco húmeda; evitar agua retenida.',wet:'La clase AC no acredita resistencia al agua. Revisar juntas y producto.',install:'Comprobar base, barrera de vapor si corresponde y dilataciones.'};
if(/spc|vinilo|linoleo/.test(n))return{family:'Resilientes',care:'Limpieza suave según fabricante; proteger de arrastre y calor.',wet:'La aptitud del conjunto depende de juntas, soporte y sistema; no equivale a impermeabilización.',install:'Soporte plano, humedad admisible y compatibilidad con calefacción.'};
if(/porcelanico|azulejo|hexagonal/.test(n))return{family:'Cerámica',care:'Limpiar superficie y juntas con productos compatibles.',wet:'Confirmar uso como pavimento y resistencia al deslizamiento; especial atención a ducha.',install:'Adhesivo, juntas y soporte adecuados al formato; impermeabilizar donde proceda.'};
if(/microcemento|cemento pulido/.test(n))return{family:'Continuos',care:'Cuidar el sellado y evitar abrasivos; mantenimiento según sistema.',wet:'No basta el nombre del acabado: revisar sellado e impermeabilización.',install:'Evaluar fisuras, juntas del soporte y aplicación por capas.'};
if(/marmol|piedra|travertino|pizarra|terrazo|hidraulica|ladrillo/.test(n))return{family:'Piedra y minerales',care:'Evitar ácidos en materiales sensibles; consultar sellado y manchas.',wet:'Porosidad y deslizamiento dependen de piedra, acabado y tratamiento.',install:'Confirmar espesor, peso, juntas, soporte y sellador compatible.'};
if(/moqueta/.test(n))return{family:'Textiles',care:'Aspirar y tratar las manchas según la fibra.',wet:'Evitar humedad persistente; revisar uso y secado.',install:'Comprobar base, fijación y encuentros con otros pavimentos.'};
return{family:'Madera y naturales',care:'Evitar agua retenida y proteger patas de muebles; mantener el acabado.',wet:'La madera, el bambú y el corcho requieren verificar producto y condiciones de uso.',install:'Aclimatación, humedad del soporte y juntas de dilatación.'};}
const families=['all','Madera y naturales','Laminado','Resilientes','Cerámica','Continuos','Piedra y minerales','Textiles','Propio'];
function sample(x){return `<div class="ml-sample ml-pattern-${safe(x.kind||'tile')}" style="--ml-color:${validColor(x.color||x.tone)}" aria-label="Muestra de color y patrón de ${safe(x.name)}"></div>`;}
function entries(){if(tab==='floors')return allFloors();if(tab==='colors')return colorOptions.map((x,i)=>({id:'color-'+i,name:x[1],color:x[0],kind:'plain',note:x[0].toUpperCase()}));if(tab==='walls')return wallFinishes.map((name,i)=>({id:'wall-'+i,name,color:'#d9ceba',kind:/listonado/i.test(name)?'wood':/marmol/i.test(name)?'marble':/azulejo/i.test(name)?'tile':'plain',note:'Acabado de pared · confirma el soporte y el sistema.'}));return bathOptions.map((x,i)=>({...x,id:'bath-'+i,color:x.tone,note:x.note}));}
function roomOptions(){const rooms=tab==='baths'?project.rooms.filter(r=>roomType(r)==='bath'):project.rooms;return rooms.map(r=>`<option value="${safe(r.id)}">${safe(r.name)}</option>`).join('')+`<option value="new">Nueva estancia${tab==='baths'?' de baño':''}</option>`;}
function render(){const host=q('#view-materials');if(!host)return;const oldTarget=target;const list=entries().filter(x=>(tab!=='floors'||family==='all'||facts(x).family===family)&&norm(x.name+' '+(x.note||'')+' '+(tab==='floors'?facts(x).family:'')).includes(norm(query)));compare=compare.filter(id=>allFloors().some(x=>x.id===id));host.innerHTML=`<div class="page-head"><div><div class="crumb">TU CASA / BIBLIOTECA DE MATERIALES</div><h1>Elige con los ojos. Decide con criterio.</h1><p>Explora acabados, compara hasta tres suelos y lleva tu elección a una estancia.</p></div><button class="btn btn-dark" id="mlAdd">＋ Tu propio suelo</button></div><div class="ml-toolbar"><div class="ml-tabs" aria-label="Familias de acabados">${[['floors','Suelos'],['colors','Colores'],['walls','Paredes'],['baths','Baños']].map(([id,name])=>`<button type="button" data-ml-tab="${id}" aria-pressed="${tab===id}">${name}</button>`).join('')}</div><div class="ml-filters"><label>Buscar material<input id="mlSearch" type="search" placeholder="Roble, verde, microcemento…" value="${safe(query)}"></label>${tab==='floors'?`<label>Familia<select id="mlFamily">${families.map(f=>`<option value="${f}" ${family===f?'selected':''}>${f==='all'?'Todas las familias':f}</option>`).join('')}</select></label>`:''}<label>Aplicar en<select id="mlRoom">${roomOptions()}</select></label></div></div><p class="ml-explainer">Muestras esquemáticas de color y textura. El tono real cambia con la luz y la pantalla: confirma una muestra física antes de comprar.</p><div class="ml-results-head"><strong>${list.length} ${list.length===1?'opción':'opciones'}</strong>${tab==='floors'?`<button class="btn btn-light" id="mlCompareJump" ${compare.length?'':'disabled'}>Ver comparación (${compare.length}/3)</button>`:''}</div><div class="ml-grid">${list.map(x=>`<article class="ml-card">${sample(x)}<div class="ml-card-body"><span class="ml-category">${tab==='floors'?facts(x).family:tab==='colors'?'Color de pared':tab==='walls'?'Revestimiento':'Ambiente de baño'}</span><h2>${safe(x.name)}</h2><p>${safe(tab==='floors'?(x.custom?x.note||'Material añadido por ti':facts(x).care):x.note)}</p><div class="ml-card-actions"><button class="btn btn-dark" data-ml-use="${safe(x.id)}">Aplicar</button>${tab==='floors'?`<button class="btn btn-light" data-ml-compare="${safe(x.id)}" aria-pressed="${compare.includes(x.id)}">${compare.includes(x.id)?'✓ Comparando':'Comparar'}</button>`:''}${x.custom?`<button class="btn btn-light" data-ml-edit="${safe(x.id)}">Editar</button>`:''}</div></div></article>`).join('')||'<div class="ml-empty"><h2>No hay coincidencias</h2><p>Prueba otro nombre o vuelve a todas las familias. También puedes crear tu propio suelo.</p><button class="btn btn-light" id="mlClear">Limpiar filtros</button></div>'}</div><div id="mlComparison"></div>`;
const select=q('#mlRoom');if([...select.options].some(o=>o.value===oldTarget))select.value=oldTarget;else if([...select.options].some(o=>o.value===selectedRoom()?.id))select.value=selectedRoom().id;target=select.value;select.onchange=()=>target=select.value;
q('#mlAdd').onclick=()=>edit();qa('[data-ml-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.mlTab;query='';render();});q('#mlSearch').oninput=e=>{query=e.target.value;const start=e.target.selectionStart;render();q('#mlSearch').focus();q('#mlSearch').setSelectionRange(start,start);};if(q('#mlFamily'))q('#mlFamily').onchange=e=>{family=e.target.value;render();};if(q('#mlClear'))q('#mlClear').onclick=()=>{query='';family='all';render();};qa('[data-ml-use]').forEach(b=>b.onclick=()=>apply(entries().find(x=>x.id===b.dataset.mlUse)));qa('[data-ml-edit]').forEach(b=>b.onclick=()=>edit(custom().find(x=>x.id===b.dataset.mlEdit)));qa('[data-ml-compare]').forEach(b=>b.onclick=()=>{const id=b.dataset.mlCompare;if(compare.includes(id))compare=compare.filter(x=>x!==id);else if(compare.length<3)compare.push(id);else return toast('Ya comparas tres suelos. Quita uno para añadir otro.');render();});if(q('#mlCompareJump'))q('#mlCompareJump').onclick=()=>q('#mlComparison').scrollIntoView({behavior:'smooth',block:'start'});renderComparison();}
function renderComparison(){const list=compare.map(id=>allFloors().find(x=>x.id===id)).filter(Boolean);q('#mlComparison').innerHTML=list.length?`<section class="ml-comparison"><div class="ml-results-head"><div><span class="crumb">DECISIÓN DE MATERIALES</span><h2>Compara antes de elegir</h2></div><button class="btn btn-light" id="mlEmptyCompare">Vaciar comparación</button></div><p>Orientación por familia, sin marcas ni prestaciones certificadas. Verifica siempre la ficha del producto concreto.</p><div class="ml-compare-grid" style="--ml-columns:${list.length}">${list.map(x=>{const f=facts(x);return `<article class="ml-compare-card">${sample(x)}<h3>${safe(x.name)}</h3><dl><dt>Familia</dt><dd>${safe(f.family)}</dd><dt>Limpieza y cuidado</dt><dd>${safe(f.care)}</dd><dt>Humedad y baño</dt><dd>${safe(f.wet)}</dd><dt>Antes de instalar</dt><dd>${safe(f.install)}</dd>${x.custom?`<dt>Tus notas</dt><dd>${safe(f.note)}</dd>`:''}</dl><button class="btn btn-dark" data-ml-pick="${safe(x.id)}">Elegir este suelo</button><button class="btn btn-light" data-ml-remove="${safe(x.id)}">Quitar de comparación</button></article>`;}).join('')}</div></section>`:'';qa('[data-ml-pick]').forEach(b=>b.onclick=()=>apply(allFloors().find(x=>x.id===b.dataset.mlPick),'floors'));qa('[data-ml-remove]').forEach(b=>b.onclick=()=>{compare=compare.filter(id=>id!==b.dataset.mlRemove);render();});if(q('#mlEmptyCompare'))q('#mlEmptyCompare').onclick=()=>{compare=[];render();};}
function apply(x,category=tab){if(!x)return;let r=project.rooms.find(r=>r.id===target);checkpoint();if(!r)r=createDesignRoom(false,category==='baths'?'Baño':'Salón',category==='baths'?'bath':'living');project.selectedRoom=project.rooms.findIndex(v=>v.id===r.id);loadDesignDraft(r);if(category==='floors')Object.assign(designDraft,{material:x.name,floorColor:validColor(x.color),floorKind:x.kind,materialNote:x.custom?x.note||'':''});if(category==='colors')Object.assign(designDraft,{wallColor:x.color,wallName:x.name});if(category==='walls')designDraft.wallFinish=x.name;if(category==='baths')designDraft.bath=x.name;storeDesignDraft();target=r.id;goView('design');toast(x.name+' aplicado al borrador de '+r.name+'.');}
function edit(existing){q('#modal').classList.add('open');q('#modalContent').innerHTML=`<div class="crumb">TU CATÁLOGO</div><h2>${existing?'Editar':'Añadir'} suelo propio</h2><p>Guarda una referencia encontrada en tienda o una idea personal. El patrón es una representación visual.</p><form id="mlCustomForm" class="ml-custom-form"><label>Nombre del material<input name="name" required maxlength="90" value="${safe(existing?.name||'')}" placeholder="Ej. porcelánico arena de mi tienda"></label><label>Patrón visual<select name="kind">${Object.entries(kinds).map(([k,v])=>`<option value="${k}" ${existing?.kind===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Color de referencia<input type="color" name="color" value="${validColor(existing?.color)}"></label><label>Notas y datos pendientes<textarea name="note" maxlength="800" rows="4" placeholder="Formato, referencia de tienda, soporte, cuidado o datos por confirmar">${safe(existing?.note||'')}</textarea></label><button class="btn btn-dark" type="submit">Guardar material</button></form>`;q('#mlCustomForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),name=String(f.get('name')).trim();if(!name)return;checkpoint();project.customMaterials=custom().map(({custom,...x})=>x);const item={id:existing?.id||'custom-'+stableRoomId(),name,kind:String(f.get('kind')),color:validColor(String(f.get('color'))),note:String(f.get('note')).trim()};const i=project.customMaterials.findIndex(x=>x.id===item.id);if(i>=0)project.customMaterials[i]=item;else project.customMaterials.push(item);saveSoon();q('#modal').classList.remove('open');tab='floors';family='Propio';query='';render();toast('Material guardado en tu proyecto.');};}
const section=document.createElement('section');section.className='view';section.id='view-materials';q('.main-content').append(section);const nav=document.createElement('button');nav.className='nav-item';nav.dataset.view='materials';nav.innerHTML='<span class="nav-icon">▦</span>Materiales';nav.onclick=()=>goView('materials');q('.nav-item[data-view="design"]').after(nav);
const previousGo=goView;goView=function(id){previousGo(id);if(id==='materials')render();};const previousRenderAll=renderAll;renderAll=function(...args){const result=previousRenderAll(...args);if(section.classList.contains('active'))render();return result;};
window.HomeAIMaterials={render,facts,allFloors};
})();
