/* HomeAI: local photograph surface simulator, no remote upload or AI claim. */
(()=>{'use strict';
const card=document.querySelector('.design-preview-card'),concept=document.querySelector('#designPreview');if(!card||!concept)return;
const style=document.createElement('style');style.textContent=`
.hai-photo-tabs{display:flex;gap:8px;padding:0 24px 18px}.hai-photo-tabs button,.hai-photo-actions button,.hai-photo-tools button{border:1px solid #d9ddd3;background:#fff;color:#263b30;border-radius:10px;padding:10px 13px;font:inherit;cursor:pointer;min-height:44px}.hai-photo-tabs button[aria-pressed=true],.hai-photo-tools button[aria-pressed=true]{background:#304f3f;color:white;border-color:#304f3f}.hai-photo{padding:0 24px 22px}.hai-photo [hidden]{display:none!important}.hai-photo-empty{padding:35px 20px;text-align:center;background:#f3f1eb;border:1px dashed #b8b8a4;border-radius:16px}.hai-photo-empty h3{font-size:23px;margin:0 0 9px}.hai-photo-empty p{color:#667064;line-height:1.6;max-width:430px;margin:0 auto 20px}.hai-photo-actions,.hai-photo-tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.hai-photo-empty .hai-photo-actions{justify-content:center}.hai-photo-actions .primary{background:#304f3f;color:white}.hai-photo-tools button:disabled,.hai-photo-actions button:disabled{opacity:.45;cursor:not-allowed}.hai-photo-stage{position:relative;background:#e7e7df;border-radius:14px;overflow:hidden}.hai-photo-stage canvas{display:block;width:100%;height:auto;touch-action:manipulation;cursor:crosshair}.hai-photo-stage canvas:focus-visible{outline:3px solid #e4b361;outline-offset:-4px}.hai-photo-badge{position:absolute;top:12px;left:12px;border-radius:20px;background:#fffE;padding:7px 12px;font-size:12px;pointer-events:none}.hai-photo-help,.hai-photo-footer{font-size:12px;line-height:1.6;color:#637063}.hai-photo-status{font-size:13px;line-height:1.5;min-height:21px;margin:8px 0;color:#365740}.hai-photo-tools label{display:flex;gap:7px;align-items:center;font-size:13px}.hai-photo-footer{padding-top:10px;border-top:1px solid #e6e7df}.hai-photo-empty .hai-photo-mark{font-size:32px;color:#486d55;margin-bottom:10px}@media(max-width:600px){.hai-photo,.hai-photo-tabs{padding-left:14px;padding-right:14px}.hai-photo-tools button{flex:1 1 auto;padding:9px}.hai-photo-empty{padding:25px 12px}.hai-photo-tabs button{flex:1;font-size:13px}}
`;document.head.append(style);
const tabs=document.createElement('div');tabs.className='hai-photo-tabs';tabs.innerHTML='<button type="button" aria-pressed="true" data-photo-tab="photo">Mi foto</button><button type="button" aria-pressed="false" data-photo-tab="concept">Ambiente conceptual</button>';
const host=document.createElement('section');host.className='hai-photo';host.setAttribute('aria-label','Simulador sobre fotografía');host.innerHTML=`<input id="haiPhotoFile" type="file" accept="image/jpeg,image/png,image/webp" hidden><div class="hai-photo-empty"><img class="hai-photo-reference" src="assets/homeai-interior.webp" alt="Imagen de inspiración; no es tu vivienda"><div class="hai-photo-mark" aria-hidden="true">▧</div><h3>Tu espacio, tus acabados</h3><p>Sube una foto, marca una pared o el suelo y prueba los colores del catálogo en tu propia habitación.</p><div class="hai-photo-actions"><button class="primary" type="button" data-photo="upload">Subir mi foto</button><button type="button" data-photo="example">Probar con un ejemplo</button></div><small>JPG, PNG o WebP · hasta 20 MB · se guarda en este navegador</small></div><div class="hai-photo-editor" hidden><div class="hai-photo-stage"><canvas tabindex="0" aria-label="Foto de la estancia. Toca las esquinas de una superficie para delimitarla. Con teclado usa flechas para mover el cursor, espacio para añadir un punto y Enter para cerrar."></canvas><span class="hai-photo-badge">Mi foto</span></div><div class="hai-photo-tools"><button type="button" data-photo="wall" aria-pressed="true">Marcar pared</button><button type="button" data-photo="floor" aria-pressed="false">Marcar suelo</button><button type="button" data-photo="finish" disabled>Cerrar superficie</button><button type="button" data-photo="cancel" disabled>Cancelar trazado</button><button type="button" data-photo="undo" disabled>Deshacer superficie</button><button type="button" data-photo="compare" aria-pressed="false">Ver original</button><label><input type="checkbox" data-photo="tiles">Mostrar juntas de suelo</label></div><p class="hai-photo-help">1. Marca las esquinas, evitando muebles. 2. Pulsa «Cerrar superficie». 3. Elige un color o suelo en el catálogo. Puedes marcar varias superficies. Teclado: flechas, espacio y Enter.</p><div class="hai-photo-actions"><button type="button" data-photo="export" class="primary">Descargar PNG</button><button type="button" data-photo="upload">Cambiar foto</button><button type="button" data-photo="remove">Quitar foto</button></div></div><p class="hai-photo-status" role="status" aria-live="polite"></p><div class="hai-photo-footer">Simulación de color y material sobre tu foto · marca las superficies. Conserva la geometría visible; los materiales son aproximados. Las fotos se guardan aparte y no se incluyen en la copia JSON del proyecto.</div>`;
concept.before(tabs,host);let tab='photo';function showTab(value){tab=value;host.hidden=value!=='photo';concept.hidden=value==='photo';concept.style.display=value==='photo'?'none':'';tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.photoTab===value)))}tabs.onclick=e=>{const b=e.target.closest('[data-photo-tab]');if(b)showTab(b.dataset.photoTab)};showTab('photo');
const q=s=>host.querySelector(s),button=k=>q(`[data-photo="${k}"]`),canvas=q('canvas'),ctx=canvas.getContext('2d');let roomId=null,record=null,img=null,points=[],surface='wall',original=false,epoch=0,uploadEpoch=0,persistQueue=Promise.resolve(),cursor={x:.5,y:.5},keyboardCursor=false;
function referencePhoto(){return ({kitchen:'assets/kitchen.webp',bath:'assets/bathroom.webp',bedroom:'assets/bedroom.webp'})[roomType(selectedRoom())]||'assets/homeai-interior.webp'}
const status=s=>q('.hai-photo-status').textContent=s;
let dbPromise;function db(){return dbPromise||(dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('homeai-photo-studio',1);request.onupgradeneeded=()=>request.result.createObjectStore('photos',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>{dbPromise=null;reject(request.error)};request.onblocked=()=>status('Cierra otras pestañas de HomeAI para activar el guardado de fotos.')}))}
async function access(mode,operation){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('photos',mode);let result;const req=operation(tx.objectStore('photos'));if(req)req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
function persist(snapshot){const item=structuredClone(snapshot);persistQueue=persistQueue.catch(()=>{}).then(()=>access('readwrite',store=>store.put(item))).then(()=>{if(roomId===item.id)status('Foto y superficies guardadas en este navegador.')}).catch(()=>{if(roomId===item.id)status('No se pudo guardar la foto: el almacenamiento puede estar lleno o bloqueado. Descarga tu PNG antes de salir.');});return persistQueue}
function decode(blob){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),i=new Image();i.onload=()=>{URL.revokeObjectURL(url);resolve(i)};i.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('No se pudo leer esta imagen. Prueba un JPG, PNG o WebP.'))};i.src=url})}
function polygon(context,pts){context.beginPath();pts.forEach((p,index)=>context[index?'lineTo':'moveTo'](p.x*canvas.width,p.y*canvas.height));context.closePath()}
function draw(showGuides=true){q('.hai-photo-empty').hidden=Boolean(img);q('.hai-photo-editor').hidden=!img;if(!img)return;canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;ctx.drawImage(img,0,0);if(!original){for(const mask of record.masks||[]){ctx.save();polygon(ctx,mask.points);ctx.clip();ctx.globalCompositeOperation='multiply';ctx.globalAlpha=.78;ctx.fillStyle=mask.kind==='floor'?(designDraft.floorColor||'#bb9976'):(designDraft.wallColor||'#e9e5dc');ctx.fillRect(0,0,canvas.width,canvas.height);if(mask.kind==='floor'&&record.tiles){ctx.globalCompositeOperation='source-over';ctx.globalAlpha=.18;ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,canvas.width/1000);const step=canvas.width/10;for(let x=0;x<canvas.width;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=step*.5){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}ctx.restore()}}
if(showGuides&&points.length){ctx.save();ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(3,canvas.width/400);polygon(ctx,points);ctx.stroke();ctx.strokeStyle='#355d46';ctx.lineWidth=Math.max(1,canvas.width/900);ctx.stroke();points.forEach(p=>{ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.x*canvas.width,p.y*canvas.height,Math.max(5,canvas.width/170),0,7);ctx.fill();ctx.stroke()});ctx.restore()}
if(showGuides&&keyboardCursor){ctx.save();ctx.strokeStyle='#ffdb5d';ctx.lineWidth=3;const x=cursor.x*canvas.width,y=cursor.y*canvas.height;ctx.beginPath();ctx.moveTo(x-12,y);ctx.lineTo(x+12,y);ctx.moveTo(x,y-12);ctx.lineTo(x,y+12);ctx.stroke();ctx.restore()}
button('finish').disabled=points.length<3;button('cancel').disabled=!points.length;button('undo').disabled=!record.masks?.length;button('compare').setAttribute('aria-pressed',String(original));button('compare').textContent=original?'Ver propuesta':'Ver original';button('tiles').checked=Boolean(record.tiles);q('.hai-photo-badge').textContent=(record.example?'Imagen de ejemplo':'Mi foto')+(original?' · Original':' · Propuesta');}
async function syncRoom(){q('.hai-photo-reference').src=referencePhoto();const next=selectedRoom()?.id||null;if(next===roomId)return;const token=++epoch;++uploadEpoch;roomId=next;record=null;img=null;points=[];original=false;draw();status(next?'Cargando foto de la estancia…':'Sube una foto para empezar.');if(!next)return;try{await persistQueue;const found=await access('readonly',s=>s.get(next));if(token!==epoch)return;if(found){const decoded=await decode(found.blob);if(token!==epoch)return;record=found;img=decoded;draw();status('Foto recuperada. Elige una superficie o un acabado.')}else status('Esta estancia aún no tiene foto.')}catch{if(token===epoch)status('No se pudo abrir el almacenamiento. Puedes trabajar y descargar el resultado.')}}
async function setPhoto(blob,example=false){if(blob.size>20*1024*1024)throw new Error('La foto supera 20 MB. Elige una imagen más pequeña.');if(!['image/jpeg','image/png','image/webp'].includes(blob.type))throw new Error('Formato no admitido. Elige JPG, PNG o WebP.');const token=++uploadEpoch;++epoch;status('Preparando la foto…');const decoded=await decode(blob);if(token!==uploadEpoch)return;if(!decoded.naturalWidth||!decoded.naturalHeight)throw new Error('La foto no tiene dimensiones válidas.');const scaled=document.createElement('canvas'),ratio=Math.min(1,1800/Math.max(decoded.naturalWidth,decoded.naturalHeight));scaled.width=Math.round(decoded.naturalWidth*ratio);scaled.height=Math.round(decoded.naturalHeight*ratio);scaled.getContext('2d').drawImage(decoded,0,0,scaled.width,scaled.height);const optimized=await new Promise(resolve=>scaled.toBlob(resolve,'image/jpeg',.9));if(!optimized)throw new Error('No se pudo preparar la foto.');const ready=await decode(optimized);if(token!==uploadEpoch)return;if(!selectedRoom())createDesignRoom(false);const id=selectedRoom().id;++epoch;roomId=id;record={id,blob:optimized,masks:[],tiles:false,example};img=ready;points=[];original=false;showTab('photo');draw();persist(record)}
q('#haiPhotoFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(record&&!confirm('¿Cambiar la foto y sus superficies de esta estancia?'))return;try{await setPhoto(f)}catch(error){status(error.message)}};
host.addEventListener('click',async e=>{const b=e.target.closest('button[data-photo]');if(!b)return;const action=b.dataset.photo;
if(action==='upload'){q('#haiPhotoFile').click();return}
if(action==='example'){try{status('Abriendo ejemplo…');const response=await fetch(referencePhoto());if(!response.ok)throw new Error('El ejemplo no está disponible. Sube tu propia foto.');let blob=await response.blob();if(!['image/jpeg','image/png','image/webp'].includes(blob.type))blob=new Blob([await blob.arrayBuffer()],{type:'image/webp'});await setPhoto(blob,true)}catch(error){status(error.message)}return}
if(!record)return;
if(action==='wall'||action==='floor'){surface=action;points=[];original=false;['wall','floor'].forEach(k=>button(k).setAttribute('aria-pressed',String(k===surface)));status('Toca las esquinas '+(surface==='wall'?'de la pared':'del suelo')+' y cierra la superficie.');draw()}
if(action==='finish')finish();if(action==='cancel'){points=[];draw();status('Trazado cancelado.')}
if(action==='undo'){record.masks.pop();points=[];draw();persist(record)}
if(action==='compare'){original=!original;draw()}
if(action==='remove'&&confirm('¿Quitar la foto y las superficies guardadas de esta estancia?')){const id=roomId;++epoch;++uploadEpoch;record=null;img=null;points=[];draw();persistQueue=persistQueue.catch(()=>{}).then(()=>access('readwrite',s=>s.delete(id))).then(()=>{if(roomId===id)status('Foto eliminada.')}).catch(()=>{if(roomId===id)status('No se pudo eliminar la foto guardada. Inténtalo de nuevo.');});}
if(action==='export'){const wasOriginal=original;original=false;draw(false);canvas.toBlob(blob=>{if(!blob){status('No se pudo descargar la imagen.');return}const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='HomeAI-simulacion.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),10000)},'image/png');original=wasOriginal;draw();status('Descarga preparada: simulación sin trazos de selección.')}
});
button('tiles').onchange=()=>{if(record){record.tiles=button('tiles').checked;draw();persist(record)}};
function addPoint(point){if(!record)return;original=false;points.push(point);draw();status(points.length+' puntos · '+(points.length>=3?'Ya puedes cerrar la superficie.':'Añade al menos 3 puntos.'))}
function finish(){if(!record||points.length<3)return;let twiceArea=0;points.forEach((p,i)=>{const n=points[(i+1)%points.length];twiceArea+=p.x*n.y-n.x*p.y});if(Math.abs(twiceArea)<.0001){status('La superficie es demasiado pequeña. Marca un área más amplia.');return}record.masks.push({kind:surface,points:points.map(p=>({...p}))});points=[];draw();persist(record)}
let pointerStart=null;canvas.addEventListener('pointerdown',e=>{pointerStart={x:e.clientX,y:e.clientY,id:e.pointerId}});canvas.addEventListener('pointercancel',()=>{pointerStart=null});canvas.addEventListener('pointerup',e=>{const start=pointerStart;pointerStart=null;if(e.button!==0||!start||start.id!==e.pointerId||Math.hypot(e.clientX-start.x,e.clientY-start.y)>12)return;keyboardCursor=false;const r=canvas.getBoundingClientRect();addPoint({x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))})});
canvas.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Enter','Escape','Backspace'].includes(e.key))e.preventDefault();if(e.key.startsWith('Arrow')){keyboardCursor=true;const step=e.shiftKey?.05:.01;cursor.x=Math.max(0,Math.min(1,cursor.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0)));cursor.y=Math.max(0,Math.min(1,cursor.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)));draw()}if(e.key===' ')addPoint({...cursor});if(e.key==='Enter')finish();if(e.key==='Escape'){points=[];draw()}if(e.key==='Backspace'){points.pop();draw()}};
const previousApply=applyFinish;applyFinish=function(...args){const result=previousApply.apply(this,args);syncRoom();if(img)draw();return result};syncRoom();
})();
