/* HomeAI: room-aware design workspace, coordinated reference looks, and work handoff. */
(()=>{'use strict';
const types={living:'Salón',kitchen:'Cocina',bath:'Baño',bedroom:'Dormitorio',dining:'Comedor',balcony:'Terraza'};
const details={
 kitchen:{
 'Distribución':['Lineal','En L','En U','Dos frentes paralelos','Con península','Con isla — comprobar pasos'],
 'Frentes':['Roble natural','Blanco mate','Verde salvia','Azul profundo','Nogal','Greige','Grafito','Terracota','Blanco con roble','Cristal acanalado'],
 'Encimera':['Porcelánico claro','Porcelánico oscuro','Cuarzo compacto','Granito','Acero inoxidable','Madera — revisar mantenimiento','Laminado compacto'],
 'Salpicadero':['Mismo material que encimera','Azulejo artesanal','Porcelánico','Vidrio','Mosaico','Azulejo vertical'],
 'Almacenaje de cocina':['Columnas hasta techo','Cajones extraíbles','Despensa independiente','Baldas abiertas','Rinconero extraíble','Combinación de cajones y columnas'],
 'Placa de cocina':['Conservar existente','Inducción','Vitrocerámica','Gas — revisar instalación'],
 'Horno y microondas':['Conservar existentes','Horno bajo encimera','Columna de horno y microondas','Horno compacto combinado'],
 'Frigorífico':['Conservar existente','Integrado','Libre instalación','Combi estrecho','Doble puerta — comprobar apertura'],
 'Lavavajillas':['Conservar existente','Integrado 45 cm','Integrado 60 cm','Libre instalación','Sin lavavajillas'],
 'Extracción de cocina':['Conservar existente','Campana mural','Campana integrada','Campana de isla','Recirculación — revisar viabilidad'],
 'Fregadero':['Una cubeta','Una cubeta con escurridor','Dos cubetas','Bajo encimera — comprobar compatibilidad'],
 'Luz de trabajo':['Bajo muebles altos','Perfil sobre encimera','Focos dirigidos','Combinación de luz general y encimera']},
 bedroom:{
 'Uso del dormitorio':['Adulto','Pareja','Adolescente','Infantil','Compartido','Invitados'],
 'Cama':['Individual 90 × 190 cm','Individual 105 × 200 cm','Doble 135 × 190 cm','Doble 150 × 200 cm','Doble 160 × 200 cm','Doble 180 × 200 cm','Cama nido','Cama baja infantil','Litera — revisar edad y altura'],
 'Cabecero':['Tapizado de lino','Madera listonada','Panel liso','Con almacenaje','Sin cabecero'],
 'Armario':['Puertas correderas','Puertas abatibles','Vestidor abierto','Mueble a medida','Armario bajo infantil'],
 'Zona de estudio':['Sin escritorio','Escritorio compacto','Mesa de estudio doble','Tocador / escritorio','Escritorio regulable'],
 'Oscurecimiento':['Cortina blackout','Estor opaco','Persiana y visillo','Estor sin cordones accesibles'],
 'Mesillas':['Dos mesillas','Una mesilla','Baldas suspendidas','Mesilla con cajones','Sin mesillas'],
 'Almacenaje de juegos':['No necesario','Cajas bajas accesibles','Banco con cajones','Estantería baja','Mueble cerrado'],
 'Iluminación de dormitorio':['Apliques de lectura','Lámpara de mesa','Luz general y lectura','Luz nocturna suave','Luz general, lectura y escritorio'],
 'Enchufes previstos':['Conservar y revisar','En cabecero','En escritorio','Cabecero y escritorio — revisar trazado'],
 'Revisión infantil':['No aplica','Revisar anclaje de muebles','Revisar ventanas, cordones y anclajes','Revisar cama según edad y fabricante'],
 'Zona libre':['Juegos en el suelo','Lectura','Ejercicio suave','Paso libre y acceso al armario']},
 living:{
 'Distribución de asientos':['Sofá recto + butaca','Sofá con chaise longue','Dos sofás enfrentados','Sofá modular','Sofá cama','Butacas sin sofá'],
 'Pared principal':['Pintura lisa','Panel de madera','Librería a medida','Galería de cuadros','Papel pintado','Revestimiento mineral'],
 'Zona de trabajo':['Sin zona de trabajo','Escritorio integrado','Mesa plegable','Escritorio tras el sofá'],
 'Televisión':['Sin televisión','Sobre mueble bajo','Panel mural — revisar soporte','Oculta en mueble'],
 'Mesa de centro':['Redonda','Ovalada','Nido','Rectangular','Puf con bandeja','Sin mesa de centro'],
 'Librería':['Sin librería','Abierta','Cerrada','Mixta','A medida hasta techo'],
 'Rincón de lectura':['Sin rincón propio','Butaca y lámpara','Banco junto a ventana','Chaise longue'],
 'Luz de salón':['General y lámpara de pie','Apliques y luz indirecta','Carril y luz de lectura','Lámparas de mesa y plafón'],
 'Organización de cables':['Canaleta discreta','Paso en mueble','Previsión en pared — revisar instalaciones','Pendiente de revisar'],
 'Tratamiento acústico decorativo':['Cortinas y alfombra','Paneles textiles','Librería con textiles','Sin tratamiento adicional'],
 'Plantas y objetos':['Pocas piezas grandes','Composición de cerámica','Plantas de interior','Arte y libros','Sin objetos añadidos'],
 'Prioridad de uso':['Conversación','Cine y televisión','Familia y juegos','Recibir invitados','Trabajo y descanso']},
 bath:{
 'Tipo de reforma':['Solo acabados','Cambio de ducha y lavabo','Reforma integral','Adaptación de accesibilidad'],
 'Configuración de baño':['Ducha','Bañera','Ducha y bañera','Aseo sin ducha'],
 'Mampara':['Fija transparente','Corredera','Abatible','Plegable','Sin mampara — revisar salpicaduras','No necesaria'],
 'Espejo':['Redondo','Rectangular','Con armario','Retroiluminado','Antivaho — revisar conexión'],
 'Ventilación':['Ventana existente','Extractor — revisar salida','Ventana y extractor','Pendiente de revisar'],
 'Revestimiento de pared':['Porcelánico gran formato','Azulejo artesanal','Mosaico','Acabado continuo apto para zona húmeda','Revestir solo zonas húmedas'],
 'Acceso a la ducha':['Conservar y revisar','A ras de suelo — revisar viabilidad','Plato de bajo perfil','Sin ducha'],
 'Apoyos de baño':['No previstos','Barras fijas — revisar anclaje','Barras abatibles — revisar soporte','Previsión de refuerzo para futuras barras'],
 'Asiento de ducha':['Sin asiento','Asiento abatible — revisar anclaje','Asiento móvil apto para ducha','Banco de obra — revisar impermeabilización'],
 'Acceso al lavabo':['Mueble con cajones','Hueco inferior libre — revisar medidas','Lavabo regulable — revisar viabilidad','Conservar y revisar'],
 'Luz de baño':['General y luz frontal de espejo','Apliques laterales de espejo','Luz indirecta y espejo','Revisar ubicación y protección según zona'],
 'Toallas y ropa':['Toallero mural','Toallero calefactable — revisar conexión','Cesto integrado','Toallero y armario de ropa blanca'],
 'Suelo de baño':['Revisar deslizamiento en mojado','Muestra y ficha técnica pendientes','Conservar suelo — revisar estado']},
 dining:{
 'Forma de mesa':['Redonda','Ovalada','Rectangular','Cuadrada','Extensible'],
 'Plazas previstas':['2 personas','4 personas','6 personas','8 personas','10 personas — comprobar espacio'],
 'Asientos':['Sillas tapizadas','Sillas de madera','Banco + sillas','Sillas apilables','Combinación de sillas'],
 'Aparador':['Sin aparador','Mueble bajo','Vitrina','A medida','Aparador estrecho'],
 'Material de mesa':['Roble','Nogal','Porcelánico','Cristal','Laminado','Madera recuperada'],
 'Iluminación sobre mesa':['Una lámpara colgante','Dos colgantes','Lámpara lineal','Plafón','Carril orientable'],
 'Decoración de pared':['Arte de gran formato','Espejo','Papel pintado','Panel de madera','Pared despejada'],
 'Almacenaje de vajilla':['En cocina','En aparador','Vitrina cerrada','Mueble mixto'],
 'Uso complementario':['Solo comer','Comer y trabajar','Juegos de mesa','Reuniones familiares'],
 'Textil de mesa':['Lino','Algodón lavable','Individuales','Sin textil habitual'],
 'Servicio auxiliar':['Sin mueble auxiliar','Carrito móvil','Consola','Barra de apoyo'],
 'Pasos alrededor de mesa':['Pendiente de medir','Medir con sillas retiradas','Revisar mesa extendida y aperturas']},
 balcony:{
 'Uso principal':['Comedor exterior','Descanso','Jardín urbano','Uso mixto','Lavadero y almacenaje'],
 'Mobiliario exterior':['Aluminio','Madera tratada','Ratán sintético','Acero protegido','Mobiliario plegable'],
 'Protección solar':['Toldo','Sombrilla','Pérgola — revisar instalación','Vela — revisar anclajes','Sin protección'],
 'Vegetación':['Macetas móviles','Jardineras','Huerto en contenedor','Plantas trepadoras — revisar soporte','Sin vegetación'],
 'Asientos exteriores':['Sofá exterior','Sillas plegables','Butacas','Banco con almacenaje','Tumbonas'],
 'Mesa exterior':['Redonda compacta','Extensible','Plegable','Auxiliar','Sin mesa'],
 'Privacidad':['Sin pantalla','Celosía — revisar anclaje','Vegetación en macetas','Panel textil apto para exterior'],
 'Luz exterior':['Apliques aptos para exterior','Lámparas portátiles de exterior','Guirnalda apta para exterior','Balizas — revisar instalación'],
 'Cojines exteriores':['Fundas lavables','Tejido apto para intemperie','Guardar textiles en interior','Sin cojines'],
 'Riego':['Manual','Goteo — revisar toma y drenaje','Autorriego en maceta','No necesario'],
 'Almacenaje exterior':['Arcón apto para exterior','Armario protegido','Banco con arcón','Sin almacenaje'],
 'Pavimento exterior':['Conservar y revisar drenaje','Porcelánico apto para exterior','Tarima exterior — revisar soporte','Losetas desmontables — revisar drenaje']}
};
const excludedDecor={bath:['furniture','diningTable','curtains','rugs','storage','textiles'],kitchen:['furniture','diningTable','rugs','textiles','storage'],bedroom:['furniture','diningTable'],dining:['furniture'],balcony:['furniture','diningTable','curtains','rugs','storage','textiles']};
const decorSpecLabels={furniture:'Asiento',diningTable:'Mesa',lighting:'Luz',textiles:'Textil',curtains:'Cortinas',rugs:'Alfombra',storage:'Almacenaje',accessories:'Detalles',hardware:'Herrajes'};
function relevantDecor(kind){return decorOptions.filter(x=>!(excludedDecor[kind]||[]).includes(x.key))}
function relevantRoomDetails(kind,values){return Object.entries(values||{}).filter(([key])=>Object.hasOwn(details[kind]||details.living,key))}
const looks=[
 {id:'deco',type:'living',name:'Contraste con carácter',subtitle:'Azul profundo, nogal y latón',image:'assets/artdeco.webp',style:'artdeco',wall:'Azul profundo',floor:'Espiga roble',decor:{textiles:'Bouclé marfil',hardware:'Latón satinado',lighting:'Latón y vidrio'},note:'Elige una pared de acento y comprueba el tono con tu luz. Revisa medidas y circulaciones antes de trasladar el mobiliario de la referencia.'},
 {id:'mineral',type:'bath',name:'Un baño cómodo y luminoso',subtitle:'Cerámica arena, ducha abierta y luz natural',image:'assets/bath-mineral.webp',style:'mediterraneo',wall:'Arena',floor:'Porcelánico antideslizante',bath:'Mediterráneo',faucet:'Níquel satinado',note:'Referencia visual: verifica pendientes, anclajes, espacio de giro y resistencia al deslizamiento. La imagen no acredita accesibilidad ni cumplimiento técnico.'},
 {id:'juvenil',type:'bedroom',name:'Un refugio con personalidad',subtitle:'Lavanda, roble y espacio para estudiar',image:'assets/teen-bedroom.webp',style:'nordico',wall:'Lavanda gris',floor:'Roble natural',decor:{textiles:'Algodón crudo',curtains:'Estor paqueto',lighting:'Luz indirecta regulable'},roomDetails:{'Zona de estudio':'Escritorio compacto'},note:'Organiza descanso, estudio y almacenaje con medidas reales. Revisa estabilidad de muebles, anclajes y seguridad de estores según la edad.'},
 {id:'natural',type:'living',name:'Natural, sin esfuerzo',subtitle:'Roble, lino y una base luminosa',image:'assets/homeai-interior.webp',style:'calido',wall:'Arena',floor:'Roble natural',decor:{textiles:'Lino natural',hardware:'Latón satinado',lighting:'Luz cálida 2700 K'},note:'Empieza por una base neutra y da protagonismo a la textura. Comprueba el tamaño del sofá y los recorridos antes de comprar.'},
 {id:'cocina',type:'kitchen',name:'Cocina mediterránea',subtitle:'Madera clara y superficies minerales',image:'assets/kitchen.webp',style:'mediterraneo',wall:'Blanco cal',floor:'Porcelánico marfil',roomDetails:{'Distribución':'En L','Frentes':'Roble natural','Encimera':'Porcelánico claro','Salpicadero':'Mismo material que encimera','Almacenaje de cocina':'Columnas hasta techo'},note:'Confirma las tomas, la apertura de puertas y los espacios de trabajo. La distribución se elige según tus medidas, no según la imagen.'},
 {id:'spa',type:'bath',name:'Un baño para desconectar',subtitle:'Salvia, terrazo y roble',image:'assets/bathroom.webp',style:'organicmodern',wall:'Salvia',floor:'Terrazo cálido',bath:'Verde sereno',faucet:'Latón cepillado',bathDetails:{shower:'Mampara fija walk-in',vanity:'Mueble suspendido',sanitary:'Inodoro suspendido',storage:'Nicho en ducha'},note:'Revisa impermeabilización, pendientes, ventilación y resistencia al deslizamiento del producto antes de aprobar materiales.'},
 {id:'descanso',type:'bedroom',name:'Calma al final del día',subtitle:'Oliva, lino y madera natural',image:'assets/bedroom.webp',style:'japandi',wall:'Oliva suave',floor:'Roble natural',decor:{textiles:'Lino lavado',curtains:'Blackout total',lighting:'Luz indirecta regulable'},roomDetails:{'Cama':'Doble 150 × 200 cm','Cabecero':'Tapizado de lino','Armario':'Puertas correderas','Zona de estudio':'Escritorio compacto','Oscurecimiento':'Cortina blackout'},note:'El tamaño de cama es una elección inicial. Mide los pasos, las puertas y la apertura del armario antes de confirmar.'}
];
function showModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open')}
function roomDialog(){showModal(`<span class="eyebrow">TU ESPACIO</span><h2>Añadir una estancia</h2><form id="roomProForm" class="pro-form"><label>Tipo de estancia<select id="roomProType" aria-label="Tipo de estancia">${Object.entries(types).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Nombre<input aria-label="Nombre de la nueva estancia" id="roomProName" required maxlength="80" value="Salón" placeholder="Ej. Dormitorio de Sara"></label><p>Empieza a diseñar ahora. Puedes añadir y confirmar las medidas en Plano cuando las tengas.</p><button class="btn btn-dark" type="submit">Crear estancia</button></form>`);let previous='Salón';$('#roomProType').onchange=e=>{if($('#roomProName').value===previous)$('#roomProName').value=types[e.target.value];previous=types[e.target.value]};$('#roomProForm').onsubmit=e=>{e.preventDefault();const name=$('#roomProName').value.trim();if(!name)return;createDesignRoom(false,name,$('#roomProType').value);$('#modal').classList.remove('open');goView('design');toast('Estancia creada: '+name)}}
const nav=document.createElement('button');nav.className='nav-item';nav.dataset.view='inspiration';nav.setAttribute('aria-label','Ambientes e inspiración');nav.innerHTML='<span class="nav-icon">◈</span>Ambientes';$('.nav-list').prepend(nav);nav.onclick=()=>goView('inspiration');
const gallery=document.createElement('section');gallery.id='view-inspiration';gallery.className='view';gallery.innerHTML=`<div class="page-head"><div><div class="crumb">HOMEAI / AMBIENTES</div><h1>Encuentra tu punto de partida.</h1><p>Elige un ambiente completo o crea tu propia combinación.</p></div><button class="btn btn-dark" id="proBlank">Diseñar desde cero</button></div><div class="look-toolbar" role="group" aria-label="Filtrar ambientes">${[['all','Todos'],['living','Salón'],['kitchen','Cocina'],['bath','Baño'],['bedroom','Dormitorio']].map(([k,l])=>`<button data-look-filter="${k}" aria-pressed="${k==='all'}">${l}</button>`).join('')}<span>Referencias creadas con IA · no son renders de tu vivienda</span></div><div class="look-grid">${looks.map(l=>`<article class="look-card" data-look-type="${l.type}"><div class="look-image"><img src="${l.image}" alt="Referencia de ${types[l.type].toLowerCase()}: ${l.subtitle}" width="1200" height="800" loading="lazy"><span>${types[l.type]}</span></div><div class="look-copy"><h2>${l.name}</h2><p>${l.subtitle}</p><div class="look-materials"><span>${l.wall}</span><span>${l.floor}</span></div><button class="btn btn-dark" data-look-open="${l.id}">Explorar este ambiente</button></div></article>`).join('')}</div><div class="look-footer"><b>Tu casa tiene sus propias medidas.</b><p>Las referencias te ayudan a elegir acabados. El estudio sobre fotos conserva tu imagen; la maqueta 3D sigue siendo conceptual.</p></div>`;$('.main-content').prepend(gallery);
$('#proBlank').onclick=roomDialog;gallery.querySelectorAll('[data-look-filter]').forEach(b=>b.onclick=()=>{gallery.querySelectorAll('[data-look-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));gallery.querySelectorAll('[data-look-type]').forEach(x=>x.hidden=b.dataset.lookFilter!=='all'&&x.dataset.lookType!==b.dataset.lookFilter)});
function openLook(id){const l=looks.find(x=>x.id===id),matches=project.rooms.filter(r=>roomType(r)===l.type);showModal(`<div class="look-dialog"><img src="${l.image}" alt="${l.name}" width="900" height="600"><span class="eyebrow">${types[l.type]} · REFERENCIA</span><h2>${l.name}</h2><p>${l.note}</p><dl><dt>Pared</dt><dd>${l.wall}</dd><dt>Suelo</dt><dd>${l.floor}</dd></dl><form id="applyLookForm" class="pro-form"><label>Aplicar a<select id="lookRoom" aria-label="Aplicar ambiente a"><option value="new">Nueva estancia: ${types[l.type]}</option>${matches.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}</select></label><p>Se cambiará el borrador. Los diseños guardados y las alternativas se conservan.</p><button class="btn btn-dark" type="submit">Usar esta combinación</button></form></div>`);$('#applyLookForm').onsubmit=e=>{e.preventDefault();const target=$('#lookRoom').value;checkpoint();if(target==='new')createDesignRoom(false,types[l.type],l.type);else project.selectedRoom=project.rooms.findIndex(r=>r.id===target);loadDesignDraft(selectedRoom());const f=floorOptions.find(x=>x.name===l.floor),color=colorOptions.find(x=>x[1]===l.wall);designDraft={...designDraft,style:l.style,wallColor:color[0],wallName:l.wall,material:f.name,floorColor:f.color,floorKind:f.kind,bath:l.bath||designDraft.bath,faucet:l.faucet||designDraft.faucet,decor:{...designDraft.decor,...l.decor},bathDetails:{...designDraft.bathDetails,...l.bathDetails},roomDetails:{...(designDraft.roomDetails||{}),...(l.roomDetails||{})}};storeDesignDraft();$('#modal').classList.remove('open');goView('design');toast('Combinación aplicada. Personalízala y guarda tu diseño.')}}
gallery.querySelectorAll('[data-look-open]').forEach(b=>b.onclick=()=>openLook(b.dataset.lookOpen));
const roomPanel=document.createElement('div');roomPanel.id='proRoomDetails';$('#decorCatalog').before(roomPanel);
const handoff=document.createElement('article');handoff.className='card pro-handoff';$('#view-design').append(handoff);
function visibleStages(){return designStages.filter(x=>x.id!=='banio'||roomType(selectedRoom())==='bath')}
updateDesignFlow=function(){const stages=visibleStages();if(!stages.some(s=>s.id===activeDesignCategory))activeDesignCategory='estilo';const i=stages.findIndex(x=>x.id===activeDesignCategory),stage=stages[i],next=stages[i+1];$('#designFlowCount').textContent=`PASO ${i+1} DE ${stages.length}`;$('#designFlowTitle').textContent=stage.title;$('#designFlowHint').textContent=stage.hint;$('.design-flow-track').setAttribute('aria-valuenow',String(i+1));$('.design-flow-track').setAttribute('aria-valuemax',String(stages.length));$('#designFlowProgress').style.width=`${(i+1)/stages.length*100}%`;$('#nextDesignStep').hidden=!next;$('#nextDesignStep').textContent=next?'Siguiente: '+({pared:'pared',suelo:'suelo',banio:'baño',decoracion:'detalles'}[next.id]||'estilo'):''};
$('#nextDesignStep').onclick=()=>{const stages=visibleStages(),next=stages[stages.findIndex(x=>x.id===activeDesignCategory)+1];if(next){setDesignCategory(next.id);filterCatalog();$('#tab-'+next.id).focus({preventScroll:true})}};
function renderDetailGroups(fields){const entries=Object.entries(fields),titles=['Decisiones principales','Personaliza tu estancia','Detalles prácticos'];return titles.map((title,index)=>{const group=entries.slice(index*4,index===2?undefined:(index+1)*4);if(!group.length)return '';return `<details class="pro-detail-group" ${index===0?'open':''}><summary>${title} · <span class="pro-detail-count">${group.filter(([key])=>designDraft.roomDetails?.[key]).length}</span>/${group.length}</summary><div class="pro-config-grid">${group.map(([key,choices])=>{const saved=designDraft.roomDetails?.[key],options=saved&&!choices.includes(saved)?[saved,...choices]:choices;return `<label>${esc(key)}<select aria-label="${esc(key)}" data-room-detail="${esc(key)}"><option value="">Por decidir</option>${options.map(o=>`<option ${saved===o?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`}).join('')}</div></details>`}).join('')}
function renderRoomExtras(){const room=selectedRoom(),kind=roomType(room),fields=details[kind]||details.living;$('#tab-banio').hidden=kind!=='bath';if(activeDesignCategory==='banio'&&kind!=='bath')setDesignCategory('estilo');$('#tab-decoracion').textContent='Detalles';$('#addDesignRoom').onclick=roomDialog;roomPanel.innerHTML=`<div class="pro-config-title"><h3>${types[kind]||'Estancia'} a tu medida</h3><p>Estas elecciones se guardan en la ficha; no modifican automáticamente los muebles de la foto.</p></div>${renderDetailGroups(fields)}`;roomPanel.querySelectorAll('select').forEach(s=>s.onchange=()=>{checkpoint();designDraft.roomDetails||={};if(s.value)designDraft.roomDetails[s.dataset.roomDetail]=s.value;else delete designDraft.roomDetails[s.dataset.roomDetail];storeDesignDraft();applyFinish();const group=s.closest('.pro-detail-group');group.querySelector('.pro-detail-count').textContent=Array.from(group.querySelectorAll('select')).filter(el=>el.value).length});$('#decorCatalog').querySelectorAll('.decor-field').forEach(el=>{const key=el.querySelector('select').dataset.decor;const exclude=excludedDecor[kind]||[];el.classList.toggle('pro-not-relevant',exclude.includes(key))});
const saved=room&&project.finishes?.[room.id];handoff.innerHTML=`<div><span class="eyebrow">DEL DISEÑO A LA OBRA</span><h2>${room?esc(room.name):'Tu estancia'}, lista para el siguiente paso</h2><p>Reúne tus decisiones y prepara las comprobaciones con el profesional que ejecutará la reforma.</p><div class="pro-readiness"><span>${room&&area(room)>0&&room.verified!==false?'✓ Medidas confirmadas':'○ Medidas pendientes'}</span><span>${saved?'✓ Diseño guardado':'○ Diseño por guardar'}</span><span>${project.tasks.some(t=>t.roomId===room?.id)?'✓ Lista de obra creada':'○ Lista de obra pendiente'}</span></div></div><div class="pro-handoff-actions"><button class="btn" id="proDossier" ${saved?'':'disabled'}>Descargar ficha de estancia</button><button class="btn btn-dark" id="proTasks" ${room?'':'disabled'}>Preparar esta estancia para obra</button><button class="btn" id="proAnother">Diseñar otra estancia</button></div>`;$('#proAnother').onclick=roomDialog;$('#proTasks').onclick=prepareRoomTasks;$('#proDossier').onclick=exportRoomSheet;
updateDesignFlow();filterCatalog()}
const previousRender=renderDesign;renderDesign=function(...args){const result=previousRender(...args);renderRoomExtras();return result};const previousFinishList=renderFinishList;renderFinishList=function(...args){const r=previousFinishList(...args);renderRoomExtras();return r};
const previousApply=applyFinish;applyFinish=function(...args){const r=previousApply(...args),kind=roomType(selectedRoom()),excludedLabels=(excludedDecor[kind]||[]).map(key=>decorSpecLabels[key]);$$('#designSpecification .spec-chip').forEach(el=>{if(excludedLabels.includes(el.querySelector('b')?.textContent))el.remove()});for(const [k,v]of relevantRoomDetails(kind,designDraft.roomDetails)){if(v){const chip=document.createElement('span');chip.className='spec-chip';chip.innerHTML=`<b>${esc(k)}</b>${esc(v)}`;$('#designSpecification').append(chip)}}return r};
function taskTemplates(kind){return [
 ['Preparación','Confirmar medidas, accesos y elementos que se conservan'],['Preparación','Revisar instalaciones y definir alcance con el profesional'],['Diseño y compras','Validar muestras reales de color y acabado'],['Diseño y compras','Comparar cotizaciones, disponibilidad y plazos'],
 ...(kind==='bath'?[['Ejecución','Revisar impermeabilización, pendientes, ventilación y desagües antes de revestir']]:kind==='kitchen'?[['Preparación','Comprobar tomas, electrodomésticos y planos de carpintería']]:kind==='balcony'?[['Preparación','Revisar drenaje, exposición exterior y anclajes']]:[['Preparación','Comprobar aperturas, pasos y dimensiones del mobiliario']]),
 ['Ejecución','Proteger superficies y coordinar el orden de instalación'],['Acabados y entrega','Revisar remates, funcionamiento y pendientes de entrega']];}
function prepareRoomTasks(){const room=selectedRoom();if(!room)return;const items=taskTemplates(roomType(room)).map(([phase,title],i)=>({phase,title:`${room.name} · ${title}`,roomId:room.id,sourceKey:`${room.id}:work:${i}`,done:false,date:'',owner:''})).filter(t=>!project.tasks.some(x=>x.sourceKey===t.sourceKey));showModal(`<span class="eyebrow">PLAN DE OBRA · ${esc(room.name)}</span><h2>${items.length?'Prepara las comprobaciones':'Lista ya preparada'}</h2><p>Lista orientativa para revisar con tu profesional. Añade responsables y fechas según el alcance real.</p><ul class="pro-task-preview">${items.map(x=>`<li>${esc(x.title.replace(room.name+' · ',''))}</li>`).join('')}</ul><button class="btn btn-dark" id="confirmRoomTasks">${items.length?'Añadir '+items.length+' tareas':'Abrir plan de obra'}</button>`);$('#confirmRoomTasks').onclick=()=>{if(items.length){checkpoint();project.tasks.push(...items);saveSoon();renderOverview()}$('#modal').classList.remove('open');goView('tasks')}}
function exportRoomSheet(){const room=selectedRoom(),d=project.finishes?.[room?.id];if(!d)return;const fields=[['Estilo',styleOptions.find(x=>x.id===d.style)?.name],['Pared',[d.wallName,d.wallFinish].filter(Boolean).join(' · ')],['Suelo',d.material],...relevantRoomDetails(roomType(room),d.roomDetails),...(roomType(room)==='bath'?[['Baño',d.bath],['Grifería',d.faucet],...bathDetailOptions.map(x=>[x.label,d.bathDetails?.[x.key]])]:[]),...relevantDecor(roomType(room)).map(x=>[x.label,d.decor?.[x.key]])];const html=`<!doctype html><html lang="es"><meta charset="utf-8"><title>HomeAI · ${esc(room.name)}</title><style>body{font:16px/1.6 system-ui;color:#183c32;max-width:850px;margin:40px auto;padding:24px}h1{font-size:36px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #ddd}th{width:35%}small{color:#52685f}@media print{body{margin:0}button{display:none}}</style><h1>HomeAI · ${esc(room.name)}</h1><p>${esc(project.title||'Mi reforma')} · ${esc(types[roomType(room)]||'Estancia')}</p><p>${area(room)>0&&room.verified!==false?fmt(area(room))+' m² confirmados':'Medidas pendientes de confirmar'}</p><h2>Diseño guardado</h2><table>${fields.filter(([,v])=>v).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')}</table><h2>Antes de ejecutar</h2><ul>${taskTemplates(roomType(room)).map(([,t])=>`<li>${esc(t)}</li>`).join('')}</ul><small>Ficha de decisiones, no plano ejecutivo ni presupuesto. Verifica medidas, muestras, compatibilidad y especificaciones de fabricantes con tu profesional. Las fotografías no se incluyen.</small></html>`;download('HomeAI-ficha-estancia.html',new Blob([html],{type:'text/html;charset=utf-8'}));toast('Ficha descargada. Puedes imprimirla o guardarla como PDF.')}
// Keep key decisions close to the catalog, with palettes available on demand.
const palette=$('.homeai-palettes');if(palette){const d=document.createElement('details');d.className='pro-palettes';const s=document.createElement('summary');s.textContent='Explorar 12 paletas coordinadas';palette.before(d);d.append(s,palette)}
$('#view-overview .page-head [data-go="design"]').textContent='Explorar ambientes';$('#view-overview .page-head [data-go="design"]').onclick=()=>goView('inspiration');
$('#view-design .page-head h1').textContent='Tu estudio de diseño';$('#view-design .page-head p').textContent='Una estancia, todas tus decisiones. Prueba, compara y guarda.';
renderDesign();if(!project.rooms.length)goView('inspiration');
})();
