/* Project-first navigation and distinct workspaces for finishes and measured layout. */
(()=>{'use strict';
const view=$('#view-design'),studio=view.querySelector('.design-studio');
const bar=document.createElement('div');bar.className='workspace-modebar';bar.innerHTML='<div class="workspace-modes" role="tablist" aria-label="Herramienta de diseño"><button role="tab" aria-selected="true" aria-controls="designFinishesWorkspace" id="modeFinishes" data-studio-mode="finishes">Colores y acabados</button><button role="tab" aria-selected="false" aria-controls="roomPlanner" id="modeLayout" data-studio-mode="layout">Distribución a escala</button></div><p id="workspaceModeHint">Prueba materiales, guarda propuestas y compara tus alternativas.</p>';studio.id='designFinishesWorkspace';studio.setAttribute('role','tabpanel');studio.setAttribute('aria-labelledby','modeFinishes');studio.before(bar);
let mode='finishes';function setMode(next){mode=next;studio.hidden=mode!=='finishes';const planner=$('#roomPlanner');if(planner){planner.hidden=mode!=='layout';planner.setAttribute('role','tabpanel');planner.setAttribute('aria-labelledby','modeLayout')}bar.querySelectorAll('[role=tab]').forEach(b=>{const active=b.dataset.studioMode===mode;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('#workspaceModeHint').textContent=mode==='layout'?'Define una estancia rectangular, coloca muebles y revisa las medidas.':'Prueba materiales, guarda propuestas y compara tus alternativas.';view.querySelector('.saved-finishes').hidden=mode==='layout';}
bar.querySelectorAll('[role=tab]').forEach(b=>{b.onclick=()=>setMode(b.dataset.studioMode);b.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const other=b.dataset.studioMode==='finishes'?'layout':'finishes';setMode(e.key==='Home'?'finishes':e.key==='End'?'layout':other);bar.querySelector('[aria-selected=true]').focus()}}});
window.addEventListener('homeai:open-planner',()=>setMode('layout'));window.addEventListener('homeai:open-finishes',()=>setMode('finishes'));setMode('finishes');
const overview=$('#view-overview');overview.querySelector('.page-head h1').textContent='Tu casa, espacio a espacio.';overview.querySelector('.page-head p').textContent='Retoma una habitación, prueba otra idea o prepara la reforma.';
const rooms=document.createElement('section');rooms.className='project-spaces';rooms.setAttribute('aria-label','Tus estancias');$('#startHub').after(rooms);
const progress=document.createElement('details');progress.className='project-progress-panel';progress.innerHTML='<summary>Medidas, presupuesto y avance de obra <span>Ver resumen</span></summary><div class="project-progress-content"></div>';rooms.after(progress);const details=progress.querySelector('div');for(const selector of ['#setupGuide','.metrics','.overview-grid','.bottom-grid']){const el=overview.querySelector(selector);if(el)details.append(el)}
const images={living:'assets/homeai-interior.webp',kitchen:'assets/kitchen.webp',bedroom:'assets/bedroom.webp',bath:'assets/bathroom.webp',dining:'assets/artdeco.webp',balcony:null};
function drawSpaces(){rooms.hidden=!project.rooms.length;progress.hidden=!project.rooms.length&&!project.planSrc;rooms.innerHTML=`<div class="project-spaces-head"><div><span class="eyebrow">MI PROYECTO</span><h2>${project.rooms.length} ${project.rooms.length===1?'estancia':'estancias'} para diseñar</h2></div><button class="btn btn-dark" id="workspaceAddRoom">＋ Nueva estancia</button></div><div class="project-space-grid">${project.rooms.map((r,i)=>{const design=project.finishes?.[r.id]||project.designDrafts?.[r.id],image=images[roomType(r)],measured=area(r)>0&&r.verified!==false;return `<article class="project-space"><div class="project-space-image">${image?`<img src="${image}" alt="Referencia decorativa para ${esc(r.name)}" loading="lazy"><span>Imagen de referencia</span>`:'<div class="project-space-placeholder">Terraza</div>'}</div><div class="project-space-copy"><h3>${esc(r.name)}</h3><p>${measured?fmt(area(r))+' m² confirmados':'Medidas por confirmar'} · ${project.finishes?.[r.id]?'Diseño guardado':'En preparación'}</p>${design?`<div class="project-space-swatches"><i style="background:${/^#[0-9a-f]{6}$/i.test(design.wallColor)?design.wallColor:'#ddd'}"></i><span>${esc(design.wallName||'Color elegido')} · ${esc(design.material||'Suelo pendiente')}</span></div>`:'<p>Empieza por la distribución o los acabados.</p>'}<div class="project-space-actions"><button class="btn btn-dark" data-room-open="${i}">Diseñar</button><button class="btn btn-light" data-room-layout="${i}">Distribuir muebles</button></div></div></article>`}).join('')}</div>`;$('#workspaceAddRoom').onclick=()=>$('#addDesignRoom').click();rooms.querySelectorAll('[data-room-open],[data-room-layout]').forEach(b=>b.onclick=()=>{project.selectedRoom=Number(b.dataset.roomOpen??b.dataset.roomLayout);goView('design');setMode(b.hasAttribute('data-room-layout')?'layout':'finishes');saveSoon()})}
const oldOverview=renderOverview;renderOverview=function(...args){const result=oldOverview(...args);drawSpaces();return result};drawSpaces();
const nav=$('.nav-list');const primary=['overview','design','inspiration','materials'];const titles={overview:'Proyecto',design:'Estudio',inspiration:'Ideas',materials:'Materiales'};primary.forEach(id=>{const item=nav.querySelector(`[data-view="${id}"]`);if(item){const icon=item.querySelector('.nav-icon')?.outerHTML||'';item.innerHTML=icon+titles[id];item.classList.add('workspace-primary');nav.append(item)}});const secondary=[...nav.querySelectorAll('[data-view]')].filter(n=>!primary.includes(n.dataset.view));secondary.forEach(n=>{n.classList.add('workspace-secondary');nav.append(n)});const more=document.createElement('button');more.className='nav-item workspace-more';more.innerHTML='<span class="nav-icon" aria-hidden="true">⋯</span>Más';more.setAttribute('aria-label','Más herramientas de reforma');more.onclick=()=>{$('#modalContent').innerHTML='<span class="eyebrow">HERRAMIENTAS DE REFORMA</span><h2>Continúa tu proyecto</h2><div class="workspace-menu">'+secondary.map(n=>`<button class="btn btn-light" data-tool-view="${n.dataset.view}">${esc(n.textContent.trim())}</button>`).join('')+'</div>';$('#modal').classList.add('open');$$('[data-tool-view]').forEach(b=>b.onclick=()=>{$('#modal').classList.remove('open');goView(b.dataset.toolView)})};nav.append(more);
const oldGo=goView;goView=function(id){oldGo(id);more.classList.toggle('active',secondary.some(n=>n.dataset.view===id));if(id==='design')setMode(mode);const label=$(`.view.active .page-head h1`);if(label){label.tabIndex=-1;label.focus({preventScroll:true})}};
$('#helpBtn').onclick=()=>{$('#modalContent').innerHTML='<span class="eyebrow">HOMEAI · GUÍA RÁPIDA</span><h2>Diseña en cuatro pasos</h2><ol class="workspace-help"><li><b>Crea una estancia.</b> Empieza con una habitación o abre una referencia desde Ideas.</li><li><b>Prueba su distribución.</b> En Estudio → Distribución a escala, introduce las medidas y coloca muebles. Las piezas son volúmenes orientativos.</li><li><b>Elige los acabados.</b> Compara suelos en Materiales, guarda favoritos y prueba colores sobre una foto.</li><li><b>Prepara la obra.</b> Guarda la propuesta y descarga su ficha. En Más encontrarás plano, presupuesto, tareas y archivos.</li></ol><p>El proyecto se conserva en este navegador. Exporta una copia para guardarlo fuera de este dispositivo.</p>';$('#modal').classList.add('open')};
goView('overview');
})();
